const square = document.querySelectorAll('.square');
const mole = document.querySelectorAll('.mole');
const timeLeft = document.querySelector('#time-left');
let score = document.querySelector('#score');
const button = document.querySelector('button');

let result = 0;
let timeLimit = 60;
let currentTime = timeLimit;
timeLeft.textContent = timeLimit;
let timerId;
let moleAppear;


function randomSquare(){
    square.forEach(className => {
        className.classList.remove('mole');
    })

    let randomPosition = square[Math.floor(Math.random() * 9)];
    // Math.floor rounds down random number generated by Math.random * 9

    randomPosition.classList.add('mole');

    //assign the id of the randomPosition to hitPosition for us to use later
    hitPosition = randomPosition.id; 
    //randomPosition.id is randomly selected from square id in html
}

square.forEach(id =>{
    id.addEventListener('mouseup',() =>{
        if(id.id === hitPosition){
            result = result + 1;
            score.textContent = result; 
            // textContent visually display result in score in html
        }
    })

})

function moveMole(){
    timerId = setInterval(countDown,1000);
    console.log(timerId);
    moleAppear = setInterval(randomSquare, (Math.random()*200 + 600 ));
    button.style.visibility = "hidden";
}

function countDown(){
    currentTime--; // to change starting time change in HTML file
    timeLeft.textContent = currentTime;

    if(currentTime === 0){
        clearInterval(timerId);
        clearInterval(moleAppear);
        alert('Game Over :(, your final score is ' + result + '. Refresh to start again.');
        button.style.visibility = "visible";
        timeLeft.textContent = timeLimit;
        currentTime = timeLimit;
        result = 0;
        score.textcontent = result;
    }
}
//let timerId = setInterval(countDown,1000);
//moveMole();

